# Generated by Django 3.1.3 on 2021-01-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('subjectid', models.IntegerField(primary_key=True, serialize=False)),
                ('subname', models.CharField(max_length=60)),
                ('senmister', models.CharField(max_length=60)),
                ('year', models.CharField(max_length=60)),
                ('branch', models.CharField(max_length=60)),
                ('reg', models.CharField(max_length=60)),
            ],
        ),
    ]
