# Generated by Django 3.1.3 on 2021-01-03 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='docfile',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
